import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import './globals.css'

import { ApolloClientWrapper } from '@/components/common/apollo-client.wrapper'
import { Footer } from '@/components/common/footer'
import { Header } from '@/components/common/header'
import { Toaster } from '@/components/ui/toaster'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ApolloClientWrapper>
          <Header />
          {children}
          <Footer />
        </ApolloClientWrapper>
        <Toaster />
      </body>
    </html>
  )
}
